_target_: src.models.retina_mnist_module.RetinaMNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.timm_classifier.TimmClassifier
  model_name: convnext_tiny
  num_classes: 5
  pretrained: false
  drop_rate: 0.0
  drop_path_rate: 0.1

num_classes: 5

compile: false